Assets/Prefabs/Gun.meta, Assets/Prefabs/Gun/Bullet.prefab, Assets/Prefabs/Gun/Bullet.prefab.meta, Assets/Scenes/GunTestScene.unity, Assets/Scenes/GunTestScene.unity.meta, Assets/Scripts/Gun/Bullet.cs, Assets/Scripts/Gun/Bullet.cs.meta, Assets/Scripts/Gun/Gun.cs, Assets/Scripts/Gun/Gun.cs.meta
=> [ADD] 총알 발사 및 리로드

Assets/Scenes/test.unity
=> [Update] scene

Assets/Externals/HQ Shipping Container (Modular)/HQ Shipping Container (Modular) Mobile Package/HQ Shipping Container (Modular) Mobile Package.unitypackage.meta, Assets/Externals/LowPolyFPSLite/LowPolyFPSLite_2021.3.0_HDRP_v1.0.unitypackage.meta, Assets/Externals/LowPolyFPSLite/LowPolyFPSLite_2021.3.0_URP_v1.0.unitypackage.meta, Assets/Scripts/Managers/TargetSpawnManager.cs
과녁이 하나의 위치에 중첩돼 생성되는 버그를 수정했습니다.
=> [UPDATE] RE_TARGET POOL BUGFIX

Assets/Prefabs/JB_Prefabs/Player 1.prefab, Assets/Prefabs/JB_Prefabs/Player 1.prefab.meta, Assets/Prefabs/JB_Prefabs/Player.prefab, Assets/Scripts/Player/Camera.meta, Assets/Scripts/Player/Camera/CameraMove.cs, Assets/Scripts/Player/Camera/CameraMove.cs.meta, ProjectSettings/Packages/com.unity.probuilder/Settings.json
=> [ADD] Player Camera

Assets/Externals/HQ Shipping Container (Modular)/HQ Shipping Container (Modular) Mobile Package/HQ Shipping Container (Modular) Mobile Package.unitypackage.meta, Assets/Prefabs/JB_Prefabs/Player 1.prefab.meta, Assets/Scenes/MainSceneTargetSpawnTest.unity, Assets/Scenes/MainSceneTargetSpawnTest.unity.meta, Assets/Scripts/Managers/TargetSpawnManager.cs, Assets/Scripts/UI/Menu/TargetSpawnTrigger.cs, Assets/Scripts/UI/Menu/TargetSpawnTrigger.cs.meta
1. Target Spawn Trigger 스크립트 생성
2. Target Spawn Manager 스크립트 수정 (주석 달아놓았음)
3. 트리거가 발동되면 타겟이 생성되고 트리거는 비활성화됨, 해당 세션의 타겟이 전부 파괴되어 사라지면 or 180초가 지나면 트리거가 다시 활성화됨 (3.의 내용은 아직 작업안된내용임)
=> [ADD] Spawn Point Trigger Added

Assets/Scripts/Gun/Gun.cs, Assets/Scripts/Managers/GunManager.cs
=> [Sub] 애니메이션 수정필요하여 뺌

Assets/Scripts/Gun/Gun.cs, Assets/Scripts/Managers/GunManager.cs, Assets/Scripts/UI/Menu/AmmosUI.cs
=> [edit] 총기 별 탄약 상황 수정

Assets/Scripts/Gun/Gun.cs
=> [edit]리로드 관련 부분 수정

Assets/Scenes/MainScene.unity, Assets/Scenes/StartScene.unity, Assets/Scripts/Gun/Gun.cs, Assets/Scripts/UI/Menu/AmmosUI.cs
- 재장전 부분 UI 업데이트
- 총기 재장전 코드 수정
=> [UPDATE] Reload

Assets/Scripts/Gun/Gun.cs
=> [edit] 발사 오류

Assets/Scripts/Gun/Gun.cs, Assets/Scripts/Managers/GunManager.cs
=> [edit] 스나이퍼 딜레이 안되는 부분 수정

Assets/Scenes/MainScene.unity
=> [UPDATE] MAP

Assets/Scripts/Gun/Gun.cs
=> [edit] 3연사 연사 탄창 안빠짐 오류 수정

Assets/Scripts/Gun/Bullet.cs, Assets/Scripts/Gun/Gun.cs
=> [edit]총알 벽에 부딪힐시 파괴

Assets/Scripts/Gun/Gun.cs
=> [edit] 딜레이 재수정

Assets/Scripts/Gun/Gun.cs
=> [edit]연사 문제 해결

Assets/Scripts/Gun/Gun.cs
=> [FIX] Brust Mode UI FIX

Assets/Animations/AR.anim, Assets/Animations/AR.anim.meta, Assets/Animations/SR.anim, Assets/Animations/SR.anim.meta, Assets/Scripts/Gun/Gun.cs
=> [edit]3연발 및 연사 애니메이션 추가

Assets/Scripts/Gun/Gun.cs
=> [edit]gun.CS 최적화

Assets/Animations/AR.anim.meta, Assets/Animations/SR.anim.meta, Assets/Externals/HQ Shipping Container (Modular)/HQ Shipping Container (Modular) Mobile Package/HQ Shipping Container (Modular) Mobile Package.unitypackage.meta, Assets/Externals/LowPolyFPSLite/LowPolyFPSLite_2021.3.0_HDRP_v1.0.unitypackage.meta, Assets/Externals/LowPolyFPSLite/LowPolyFPSLite_2021.3.0_URP_v1.0.unitypackage.meta, Assets/Scripts/Gun/Gun.cs, Assets/Scripts/Managers/AudioManager.cs, Assets/Scripts/Managers/GameManager.cs
1. SFX
- 효과음 중복 재생 가능
2. GUN
- 타겟을 파괴시키기 위해 총알 생존 시간 및 리로드 시간 수정
=> [UPDATE] SFX, GUN

.idea/.idea.AimTrainer/.idea/indexLayout.xml, .idea/.idea.AimTrainer/.idea/workspace.xml, Assets/Scripts/Gun/Gun.cs
=> [edit]3연발 오류 수정

Assets/Scripts/Managers/DialogueManager.cs
=> [BUGFIX] 대사창
